version: "3.8"
services:
  frontend:
    build:
      context: ./frontend/QuickThought
    ports:
      - "5173:5173" # Exposing frontend on port 5173
    volumes:
      - ./frontend/QuickThought:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Exposing backend on port 5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py # Ensure Flask knows which file to run
      - FLASK_ENV=development # Set environment to development (can be production in deployment)
      - DATABASE_URI=mysql+pymysql://root:100123@db:3306/QuickThought # Use db service as host
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 100123
      MYSQL_DATABASE: QuickThought
    ports:
      - "33061:3306" # Exposing MySQL on port 33061 externally, but container uses 3306
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
