# Removed `version` as it's no longer required in modern Compose
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Expose Flask backend on port 5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URI=mysql+pymysql://root:100123@db:3306/QuickThought # Database URI
      - FIREBASE_CONFIG_PATH=/app/config/firebase_config.json
    depends_on:
      - db
    networks:
      - quickthought_network # Connect to the custom network

  db:
    image: mysql:latest
    # command: ["mysqld", "--mysql-native-password=ON"]
    # restart: unless-stopped
    ports:
      - "3306:3306" # Expose MySQL on port 3306
    environment:
      MYSQL_ROOT_PASSWORD: 100123
      MYSQL_DATABASE: QuickThought
    # volumes:
    # - db_data:/var/lib/mysql
    # If using custom configuration:
    # - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - quickthought_network

volumes:
  db_data: # Define persistent volume for MySQL
    driver: local

networks:
  quickthought_network: # Define custom network
    driver: bridge
