version: "3.8"

networks:
  quickthought_network: # Define a custom network
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend/QuickThought
    ports:
      - "5173:5173" # Exposing frontend on port 5173
    volumes:
      - ./frontend/QuickThought:/app
    depends_on:
      - backend
    networks:
      - quickthought_network

  backend:
    build:
      context: ./backend
    ports:
      - "5222:5000" # Mapping host port 5222 to container port 5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URI=mysql+pymysql://root:100123@db:3306/QuickThought
      - FIREBASE_CONFIG_PATH=/app/config/firebase_config.json
    depends_on:
      - db
    networks:
      - quickthought_network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 100123
      MYSQL_DATABASE: QuickThought
    ports:
      - "33062:3306" # Mapping host port 33062 to container port 3306
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - quickthought_network

volumes:
  db_data:
